=== DemonHe/SeekMovies/Crawler/src/templates/dtd/parse.dtd
<!ELEMENT body ((single-object|multi-objects|complex-objects|extract-url)*)>
<!ELEMENT single-object (class, attributes)>
<!ELEMENT multi-objects (root-tag, single-object)>
<!ELEMENT extract-url ( prefix?, paser_class?,location*)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT attributes (attribute+)>
<!ELEMENT attribute (tag, attr-name)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT attr-name (#PCDATA)>
<!ATTLIST tag need CDATA "text">
<!ELEMENT root-tag (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ATTLIST location type (single|all) "single">
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT paser_class (#PCDATA)>
<!ELEMENT complex-objects (root-tag, class, attributes?, loop?)>
<!ELEMENT loop (root-tag, attributes?, loop?)>

=== DemonHe/SeekMovies/out/production/Crawler/templates/doubanTemplates/douban_now_playing.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "../dtd/parse.dtd">
<body>
    <multi-objects>
        <root-tag>#nowplaying .lists</root-tag>
        <single-object>
            <class>dao.doubanEntity.ReleasingMovie</class>
            <attributes>
                <attribute>
                    <tag need = "data-title">/</tag>
                    <attr-name>movieName</attr-name>
                </attribute>
                <attribute>
                    <tag need = "data-score">/</tag>
                    <attr-name>score</attr-name>
                </attribute>
                <attribute>
                    <tag need = "data-star">/</tag>
                    <attr-name>star</attr-name>
                </attribute>
                <attribute>
                    <tag need = "data-release">/</tag>
                    <attr-name>releaseTime</attr-name>
                </attribute>
                <attribute>
                    <tag need = "data-duration">/</tag>
                    <attr-name>duration</attr-name>
                </attribute>
                <attribute>
                    <tag need = "data-region">/</tag>
                    <attr-name>region</attr-name>
                </attribute>
                <attribute>
                    <tag need = "data-director">/</tag>
                    <attr-name>director</attr-name>
                </attribute>
                <attribute>
                    <tag need = "src">.poster img</tag>
                    <attr-name>img</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <multi-objects>
        <root-tag>.tab_view>li:2 ul</root-tag>
        <single-object>
            <class>dao.doubanEntity.BoxOffice</class>
            <attributes>
                <attribute>
                    <tag>a</tag>
                    <attr-name>movieName</attr-name>
                </attribute>
                <attribute>
                    <tag>$ h1.movie_ranking_time span</tag>
                    <attr-name>startTime</attr-name>
                </attribute>
                <attribute>
                    <tag>$ h1.movie_ranking_time span</tag>
                    <attr-name>endTime</attr-name>
                </attribute>
                <attribute>
                    <tag>p:2</tag>
                    <attr-name>boxOffice</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <extract-url>
        <location type="all">#nowplaying .sbtn a</location>
    </extract-url>
</body>

=== DemonHe/SeekMovies/out/production/Crawler/templates/doubanTemplates/douban_movie_info.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "../dtd/parse.dtd">
<body>
    <single-object>
        <class>dao.doubanEntity.Movie</class>
        <attributes>
            <attribute>
                <tag>#content span:1</tag>
                <attr-name>movieName</attr-name>
            </attribute>
            <attribute>
                <tag need="href">#mainpic a</tag>
                <attr-name>movieId</attr-name>
            </attribute>
            <attribute>
                <tag>#info</tag>
                <attr-name>region</attr-name>
            </attribute>
            <attribute>
                <tag>#info</tag>
                <attr-name>language</attr-name>
            </attribute>
            <attribute>
                <tag>#info span[property$=initialReleaseDate]:1</tag>
                <attr-name>releaseDate</attr-name>
            </attribute>
            <attribute>
                <tag need="content">#info span[property$=runtime]:1</tag>
                <attr-name>during</attr-name>
            </attribute>
            <attribute>
                <tag need="src">#mainpic img</tag>
                <attr-name>poster</attr-name>
            </attribute>
            <attribute>
                <tag>strong.rating_num</tag>
                <attr-name>score</attr-name>
            </attribute>
            <attribute>
                <tag>#link-report span:1</tag>
                <attr-name>summary</attr-name>
            </attribute>
        </attributes>
    </single-object>
    <single-object>
        <class>dao.doubanEntity.MovieDirector</class>
        <attributes>
            <attribute>
                <tag need="href">#info a[rel$=directedBy]</tag>
                <attr-name>directorId</attr-name>
            </attribute>
            <attribute>
                <tag>#info a[rel$=directedBy]</tag>
                <attr-name>directorName</attr-name>
            </attribute>
            <attribute>
                <tag need="href">#mainpic a</tag>
                <attr-name>movieId</attr-name>
            </attribute>
        </attributes>
    </single-object>
    <multi-objects>
        <root-tag>.actor .attrs</root-tag>
        <single-object>
            <class>dao.doubanEntity.MovieActor</class>
            <attributes>
                <attribute>
                    <tag need="href">$ #mainpic a</tag>
                    <attr-name>movieId</attr-name>
                </attribute>
                <attribute>
                    <tag need="href">a</tag>
                    <attr-name>actorId</attr-name>
                </attribute>
                <attribute>
                    <tag>a</tag>
                    <attr-name>actorName</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <multi-objects>
        <root-tag>#info</root-tag>
        <single-object>
            <class>dao.doubanEntity.MovieTag</class>
            <attributes>
                <attribute>
                    <tag need="href">$ #mainpic a</tag>
                    <attr-name>movieId</attr-name>
                </attribute>
                <attribute>
                    <tag>[property$=genre]</tag>
                    <attr-name>tag</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <extract-url>
        <prefix>https://movie.douban.com</prefix>
        <location type="all">.actor .attrs a[rel$=starring]</location>
        <location type="all">#info a[rel$=directedBy]</location>
    </extract-url>
    <extract-url>
        <location type="single">#comments-section .pl a</location>
    </extract-url>
</body>

=== DemonHe/SeekMovies/Crawler/src/templates/doubanTemplates/douban_comment.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "../dtd/parse.dtd">
<body>
    <multi-objects>
        <root-tag>#comments</root-tag>
        <single-object>
            <class>dao.doubanEntity.Comment</class>
            <attributes>
                <attribute>
                    <tag need="href">$ .aside a</tag>
                    <attr-name>movieId</attr-name>
                </attribute>
                <attribute>
                    <tag need="title">.comment-time</tag>
                    <attr-name>commentTime</attr-name>
                </attribute>
                <attribute>
                    <tag>.comment-info a:1</tag>
                    <attr-name>commentator</attr-name>
                </attribute>
                <attribute>
                    <tag need="title">.comment-info span:3</tag>
                    <attr-name>commentLevel</attr-name>
                </attribute>
                <attribute>
                    <tag>p</tag>
                    <attr-name>comment</attr-name>
                </attribute>
                <attribute>
                    <tag need="data-cid">/</tag>
                    <attr-name>cinemaId</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <!--<extract-url>-->
        <!--<location>.next</location>-->
    <!--</extract-url>-->
</body>

=== DemonHe/SeekMovies/out/production/Crawler/templates/doubanTemplates/douban_person.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "../dtd/parse.dtd">
<body>
    <single-object>
        <class>dao.doubanEntity.Actor</class>
        <attributes>
            <attribute>
                <tag need="data-url">#opt-bar a</tag>
                <attr-name>id</attr-name>
            </attribute>
            <attribute>
                <tag>#content h1</tag>
                <attr-name>actorName</attr-name>
            </attribute>
            <attribute>
                <tag>.info</tag>
                <attr-name>sex</attr-name>
            </attribute>
            <attribute>
                <tag>.info</tag>
                <attr-name>birthDay</attr-name>
            </attribute>
            <attribute>
                <tag>.info</tag>
                <attr-name>homeLand</attr-name>
            </attribute>
            <attribute>
                <tag need="src">#headline img</tag>
                <attr-name>headPic</attr-name>
            </attribute>
            <attribute>
                <tag>span.hidden</tag>
                <attr-name>introduce</attr-name>
            </attribute>
        </attributes>
    </single-object>
</body>

=== DemonHe/SeekMovies/Crawler/src/templates/douban-ticket.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <multi-objects>
        <root-tag>#cinema-list-wrap</root-tag>
        <single-object>
            <class>dao.Cinema</class>
            <attributes>
                <attribute>
                    <tag need="data-movieId">/</tag>
                    <attr-name>movieId</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">h3</tag>
                    <attr-name>cinemaName</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">.cinema-info span:1</tag>
                    <attr-name>address</attr-name>
                </attribute>
                <attribute>
                    <tag need="href">.cinema-info span:2 a</tag>
                    <attr-name>web</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">$ #route-movieId</tag>
                    <attr-name>route</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <multi-objects>
        <root-tag>#cinema-list-wrap</root-tag>
        <single-object>
            <class>dao.Price</class>
            <attributes>
                <attribute>
                    <tag need="data-movieId">/</tag>
                    <attr-name>movieId</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">$ #content h1</tag>
                    <attr-name>movieName</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">span:1</tag>
                    <attr-name>price</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    
    <complex-objects>
        <root-tag>#cinema-list-wrap</root-tag>
        <class>dao.PriceDetail</class>
        <attributes>
            <attribute>
                <tag need="data-movieId">/</tag>
                <attr-name>movieId</attr-name>
            </attribute>
            <attribute>
                <tag need="text">$ #content h1</tag>
                <attr-name>movieName</attr-name>
            </attribute>
        </attributes>
        <loop>
            <root-tag>.versions</root-tag>
            <loop>
                <root-tag>ul</root-tag>
                <attributes>
                    <attribute>
                        <tag need="href">a</tag>
                        <attr-name>orderLink</attr-name>
                    </attribute>
                    <attribute>
                        <tag need="text">a</tag>
                        <attr-name>time</attr-name>
                    </attribute>
                </attributes>
            </loop>
        </loop>
    </complex-objects>
    
    <extract-url>
        <location>#movie-subject-page a</location>
    </extract-url>
</body>

=== DemonHe/SeekMovies/Crawler/src/templates/douban-cinema.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <single-object>
        <class>dao.Cinema</class>
        <attributes>
            <attribute>
                <tag need="text">.sp-logo a</tag>
                <attr-name>cinemaName</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.main-hd a:1</tag>
                <attr-name>reviewer</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.main-hd a:2</tag>
                <attr-name>target</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.main-hd span:3</tag>
                <attr-name>level</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.main-hd span:4</tag>
                <attr-name>date</attr-name>
            </attribute>
            <attribute>
                <tag need="text">#link-report .review-content</tag>
                <attr-name>content</attr-name>
            </attribute>
        </attributes>
    </single-object>
</body>
