=== DemonHe/SeekMovies/Crawler/src/templates/dtd/parse.dtd
<!ELEMENT body ((single-object|multi-objects|complex-objects|extract-url)*)>
<!ELEMENT single-object (class, attributes)>
<!ELEMENT multi-objects (root-tag, single-object)>
<!ELEMENT extract-url ( prefix?, paser_class?,location*)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT attributes (attribute+)>
<!ELEMENT attribute (tag, attr-name)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT attr-name (#PCDATA)>
<!ATTLIST tag need CDATA "text">
<!ELEMENT root-tag (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ATTLIST location type (single|all) "single">
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT paser_class (#PCDATA)>
<!ELEMENT complex-objects (root-tag, class, attributes?, loop?)>
<!ELEMENT loop (root-tag, attributes?, loop?)>

=== DemonHe/SeekMovies/Crawler/src/templates/taoppTemplates/taopp_now_playing.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "../dtd/parse.dtd">
<body>

    <single-object>
        <class>dao.taoppEntity.Movie</class>
        <attributes>
            <attribute>
                <tag need="text">.detail-wrap .detail-cont .center-wrap .cont-title</tag>
                <attr-name>movieName</attr-name>
            </attribute>
            <attribute>
                <tag need="data-param">div[data-spm$=w2]</tag>
                <attr-name>movieId</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-info li:4</tag>
                <attr-name>region</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-info li:5</tag>
                <attr-name>language</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-time</tag>
                <attr-name>releaseDate</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-info li:6</tag>
                <attr-name>during</attr-name>
            </attribute>
            <attribute>
                <tag need="src">.detail-wrap .detail-cont .center-wrap .cont-pic img</tag>
                <attr-name>poster</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-title .score</tag>
                <attr-name>score</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-info li:7</tag>
                <attr-name>introduction</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-info li:1</tag>
                <attr-name>directorNames</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-info li:2</tag>
                <attr-name>actorNames</attr-name>
            </attribute>
            <attribute>
                <tag>.detail-wrap .detail-cont .center-wrap .cont-info li:3</tag>
                <attr-name>tags</attr-name>
            </attribute>
        </attributes>
    </single-object>

</body>

=== DemonHe/SeekMovies/Crawler/src/templates/douban-price.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <multi-objects>
        <root-tag>#cinema-list-wrap</root-tag>
        <single-object>
            <class>dao.Price</class>
            <attributes>
                <attribute>
                    <tag need = "data-movieId">/</tag>
                    <attr-name>cinemaId</attr-name>
                </attribute>
                <attribute>
                    <tag need = "text">.hd span</tag>
                    <attr-name>price</attr-name>
                </attribute>
                <attribute>
                    <tag need = "text">.hd span</tag>
                    <attr-name>price</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
</body>

=== DemonHe/SeekMovies/Crawler/src/templates/rice-rank-coming.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <multi-objects>
        <root-tag>#flexslider2 .slides</root-tag>
        <single-object>
            <class>dao.ComingMovie</class>
            <attributes>
                <attribute>
                    <tag need="src">div img</tag>
                    <attr-name>img</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">p:1</tag>
                    <attr-name>movie</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <multi-objects>
        <root-tag>#ranklist</root-tag>
        <single-object>
            <class>dao.Rank</class>
            <attributes>
                <attribute>
                    <tag need="text">h3</tag>
                    <attr-name>movie</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">em</tag>
                    <attr-name>boxOffice</attr-name>
                </attribute>
                <attribute>
                    <tag need="src">img</tag>
                    <attr-name>img</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>

    <extract-url>
        <prefix>http://dianying.nuomi.com/movie/detail?</prefix>
        <paser_class>impls.parser.extractor.NuoMiParser</paser_class>
        <location type="all">#flexslider2 .slides li .detail</location>
        <location type="all">#flexslider1 .img</location>
    </extract-url>
</body>

=== DemonHe/SeekMovies/out/production/Crawler/templates/douban-comment-single.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <single-object>
        <class>dao.MovieComment</class>
        <attributes>
            <attribute>
                <tag need="text">.main-hd a:2</tag>
                <attr-name>movie</attr-name>
            </attribute>
            <attribute>
                <tag>.main-hd span:4</tag>
                <attr-name>time</attr-name>
            </attribute>
            <attribute>
                <tag>.main-hd span:3</tag>
                <attr-name>score</attr-name>
            </attribute>
            <attribute>
                <tag>.review-content</tag>
                <attr-name>comment</attr-name>
            </attribute>
            <attribute>
                <tag>.main-hd span:1</tag>
                <attr-name>username</attr-name>
            </attribute>
        </attributes>
    </single-object>

    <extract-url>
        <location>.total-reviews</location>
    </extract-url>
</body>

=== DemonHe/SeekMovies/out/production/Crawler/templates/doubanTemplates/douban_ticket.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "../dtd/parse.dtd">
<body>
    <complex-objects>
        <root-tag>.movie_schedule</root-tag>
        <class>dao.doubanEntity.MovieTicket</class>
        <attributes>
            <attribute>
                <tag need="href">$ .sp-logo a.logo</tag>
                <attr-name>cinemaId</attr-name>
            </attribute>
            <attribute>
                <tag need="id">$ .cover_list .now</tag>
                <attr-name>movieId</attr-name>
            </attribute>
            <attribute>
                <tag>div</tag>
                <attr-name>price</attr-name>
            </attribute>
        </attributes>
        <loop>
            <root-tag>ul</root-tag>
            <attributes>
                <attribute>
                    <tag>a</tag>
                    <attr-name>time</attr-name>
                </attribute>
                <attribute>
                    <tag need="href">a</tag>
                    <attr-name>orderLink</attr-name>
                </attribute>
            </attributes>
        </loop>
    </complex-objects>

    <single-object>
        <class>dao.doubanEntity.Cinema</class>
        <attributes>
            <attribute>
                <tag need="href">.sp-logo a.logo</tag>
                <attr-name>cinemaId</attr-name>
            </attribute>
            <attribute>
                <tag>.sp-logo a.logo</tag>
                <attr-name>cinemaName</attr-name>
            </attribute>
            <attribute>
                <tag>.bd>div</tag>
                <attr-name>route</attr-name>
            </attribute>
            <attribute>
                <tag>.bd>div</tag>
                <attr-name>address</attr-name>
            </attribute>
            <attribute>
                <tag need="href">.bd>div a</tag>
                <attr-name>web</attr-name>
            </attribute>
        </attributes>
    </single-object>
</body>

=== DemonHe/SeekMovies/Crawler/src/templates/rice-movie-info.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <single-object>
        <class>dao.Movie</class>
        <attributes>
            <attribute>
                <tag need="text">.subtitle</tag>
                <attr-name>movie</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.content p:4</tag>
                <attr-name>region</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.content p:4</tag>
                <attr-name>during</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.content p:4</tag>
                <attr-name>releaseTime</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.record span:2</tag>
                <attr-name>score</attr-name>
            </attribute>
            <attribute>
                <tag need="text">.content p:5</tag>
                <attr-name>introduce</attr-name>
            </attribute>
            <attribute>
                <tag need="src">.poster img</tag>
                <attr-name>img</attr-name>
            </attribute>
        </attributes>
    </single-object>
    <extract-url>
        <prefix>http://dianying.nuomi.com/</prefix>
        <paser_class>impls.parser.extractor.NuoMiParser2</paser_class>
        <location type="all">.recommend li .img</location>
    </extract-url>
</body>

=== DemonHe/SeekMovies/out/production/Crawler/templates/tiantang-link.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <single-object>
        <class>dao.MovieLink</class>
        <attributes>
            <attribute>
                <tag need="text">.title_all h1</tag>
                <attr-name>cinemaName</attr-name>
            </attribute>
            <attribute>
                <tag need="text">#Zoom span table tbody tr td a</tag>
                <attr-name>downloadLink</attr-name>
            </attribute>
        </attributes>
    </single-object>
</body>

=== DemonHe/SeekMovies/Crawler/src/templates/douban-info.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE body SYSTEM "dtd/parse.dtd">
<body>
    <!--<single-object>-->
        <!--<cldao.doubanEntity.ReleasingMovieovie</class>-->
        <!--<attributes>-->
            <!--<attribute>-->
                <!--<tag need="text">#content h1 span</tag>-->
                <!--<acinemaNamename>movieName</acinemaNamename>-->
            <!--</attribute>-->
            <!--<attribute>-->
                <!--<tag need="text">#info span:21</tag>-->
                <!--<acinemaNamename>duration</acinemaNamename>-->
            <!--</attribute>-->
            <!--<attribute>-->
                <!--<tag need="src">#mainpic a img</tag>-->
                <!--<acinemaNamename>img</acinemaNamename>-->
            <!--</attribute>-->
            <!--<attribute>-->
                <!--<tag need="text">#info span:12</tag>-->
                <!--<acinemaNamename>region</acinemaNamename>-->
            <!--</attribute>-->
            <!--<attribute>-->
                <!--<tag need="text">#info span:17</tag>-->
                <!--<acinemaNamename>releaseTime</acinemaNamename>-->
            <!--</attribute>-->
            <!--<attribute>-->
                <!--<tag need="text">#interest_sectl div.rating_wrap.clearbox div.rating_self.clearfix strong</tag>-->
                <!--<acinemaNamename>score</acinemaNamename>-->
            <!--</attribute>-->
            <!--<attribute>-->
                <!--<tag need="class">.rating-right div:1</tag>-->
                <!--<acinemaNamename>star</acinemaNamename>-->
            <!--</attribute>-->
        <!--</attributes>-->
    <!--</single-object>-->
    <multi-objects>
        <root-tag>#info span:1 .attrs</root-tag>
        <single-object>
            <class>dao.Director</class>
            <attributes>
                <attribute>
                    <tag need="text">$ #content h1 span</tag>
                    <attr-name>movie</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">a</tag>
                    <attr-name>cinemaName</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
    <multi-objects>
        <root-tag>#info .actor .attrs</root-tag>
        <single-object>
            <class>dao.Actor</class>
            <attributes>
                <attribute>
                    <tag need="text">$ #content h1 span</tag>
                    <attr-name>movie</attr-name>
                </attribute>
                <attribute>
                    <tag need="text">span a</tag>
                    <attr-name>cinemaName</attr-name>
                </attribute>
            </attributes>
        </single-object>
    </multi-objects>
</body>
